#!/usr/bin/env php
<?php
/**
 * Load wordpress environment
 */
function find_wordpress_base_path() {
    $dir = dirname(__FILE__);
    do {
        // it is possible to check for other files here
        if( file_exists($dir."/wp-config.php") ) {
            return $dir;
        }
    } while( $dir = realpath("$dir/..") );
    return null;
}
define( 'BASE_PATH', find_wordpress_base_path(). "/" );
global $wp, $wp_query, $wp_the_query, $wp_rewrite, $wp_did_header;
require(BASE_PATH . 'wp-load.php');

// Composer autoload
require __DIR__ . '/vendor/autoload.php';

// Load the Environment file
$dotenv = new \Dotenv\Dotenv(__DIR__);
if (file_exists(__DIR__ . '/.env')) {
    $dotenv->load();
}

// Kickstart custom engine
$engine = new EvolveEngine\Core\Application(ABSPATH . '../../', __DIR__);
$engine->start();

// Run the console application
$engine->make(EvolveEngine\Console\ConsoleApplication::class)
    ->boot()
    ->run();
